name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # Start building our array of files to attach
          # main.js and manifest.json are always required
          files=("main.js" "manifest.json")
          
          # Only include styles.css if it exists and is greater than 0 bytes
          if [ -s "styles.css" ]; then
            files+=("styles.css")
          fi

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            "${files[@]}"
